---
functional:
  - Пользователь может самостоятельно создавать игру или вступать в существующую
  - Пользователь может соревноваться с другими игроками в режиме онлайн
  - Пользователь может соревноваться с ботом
  - Пользователь может выбирать сложность игры
  - Пользователь может войти в запущенную игру в качестве зрителя
  - Пользователь может общаться в чате со зрителями во время игры
  - Пользователь может выбрать язык, на котором будет писать код
  - Пользователь может выбрать продолжительность раунда
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
