---
functional:
  - Пользователь может самостоятельно создавать игру или вступать в существующую
  - В игру можно играть с любым человеком, с ботом или другом
  - Решение задачи на скорость против другого игрока. Оба игрока видят друг у друга редактор с кодом, вывод тестов, могут менять язык программирования во время решения
  - Можно выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Пользователь может войти в запущенную игру в качестве зрителя
  - Пользователь может общаться в чате со зрителями во время игры
  - Пользователь может выбрать язык, на котором будет писать код
  - Пользователь может выбрать продолжительность раунда
  - Пользователь должен иметь возможность получать очки, на основе которых должен строиться рейтинг за неделю, месяц и за все время
  - Пользователь должен иметь возможность переподключиться в игру в любой момент, пока она не закончена, если он вылетел из нее
  - Завершенная игра доступна в записи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
 - Игрок не может редактировать код противника
